language: node_js
node_js:
  - "14.15.3"

jobs:
  include:
    - name: "Lint"
      env: TEST_COMMAND=lint
    - name: "Unit tests"
      env: TEST_COMMAND=test:jest
    - name: "E2E tests"
      env: TEST_COMMAND=test:cypress
      before_script:
        - npm run build
        - npm run start & # start a Web server
        - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - npm run $TEST_COMMAND

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
